import type { CheckupData } from "./types";

/**
 * 데모용 예시 데이터.
 *
 * CANDiY API Key 없이도 대시보드 화면을 확인할 수 있도록 제공한다.
 * 실제 응답 스키마(개발가이드 /docs/nhis/checkup)와 동일한 형태이며,
 * 값은 판정 색상(정상/주의/위험)이 모두 드러나도록 구성한 가상의 수치다.
 */
export const DEMO_CHECKUP_DATA: CheckupData = {
  patientName: "김건강",
  overviewList: [
    {
      checkupDate: "2025-04-18",
      height: "173",
      weight: "78",
      waists: "88",
      BMI: "26.1",
      vision: "1.0/1.0",
      hearing: "정상",
      bloodPressure: "138/88",
      proteinuria: "음성",
      hemoglobin: "15.2",
      fastingBloodGlucose: "131",
      totalCholesterol: "215",
      HDLCholesterol: "48",
      triglyceride: "182",
      LDLCholesterol: "142",
      serumCreatinine: "0.9",
      GFR: "94",
      AST: "34",
      ALT: "46",
      yGPT: "71",
      chestXrayResult: "정상",
      osteoporosis: "",
      evaluation: "주의",
    },
    {
      checkupDate: "2023-05-02",
      height: "173",
      weight: "75",
      waists: "85",
      BMI: "25.1",
      vision: "1.0/1.2",
      hearing: "정상",
      bloodPressure: "129/82",
      proteinuria: "음성",
      hemoglobin: "15.0",
      fastingBloodGlucose: "104",
      totalCholesterol: "198",
      HDLCholesterol: "52",
      triglyceride: "156",
      LDLCholesterol: "128",
      serumCreatinine: "0.9",
      GFR: "98",
      AST: "29",
      ALT: "35",
      yGPT: "54",
      chestXrayResult: "정상",
      osteoporosis: "",
      evaluation: "정B",
    },
    {
      checkupDate: "2021-06-11",
      height: "173",
      weight: "71",
      waists: "81",
      BMI: "23.7",
      vision: "1.2/1.2",
      hearing: "정상",
      bloodPressure: "118/74",
      proteinuria: "음성",
      hemoglobin: "14.8",
      fastingBloodGlucose: "92",
      totalCholesterol: "176",
      HDLCholesterol: "61",
      triglyceride: "110",
      LDLCholesterol: "104",
      serumCreatinine: "0.8",
      GFR: "102",
      AST: "24",
      ALT: "22",
      yGPT: "31",
      chestXrayResult: "정상",
      osteoporosis: "",
      evaluation: "정A",
    },
  ],
  referenceList: [
    {
      refType: "단위",
      height: "Cm",
      weight: "Kg",
      waists: "Cm",
      BMI: "kg/m2",
      bloodPressure: "mmHg",
      hemoglobin: "g/dL",
      fastingBloodGlucose: "mg/dL",
      totalCholesterol: "mg/dL",
      HDLCholesterol: "mg/dL",
      triglyceride: "mg/dL",
      LDLCholesterol: "mg/dL",
      serumCreatinine: "mg/dL",
      GFR: "mL/min",
      AST: "U/L",
      ALT: "U/L",
      yGPT: "U/L",
    },
    {
      refType: "정상(A)",
      BMI: "18.5-24.9",
      waists: "남90미만 여85미만",
      bloodPressure: "120/80 미만",
      hemoglobin: "남13-16.5 여12-15.5",
      fastingBloodGlucose: "100 미만",
      totalCholesterol: "200 미만",
      HDLCholesterol: "60 이상",
      triglyceride: "150 미만",
      LDLCholesterol: "130 미만",
      serumCreatinine: "1.5 이하",
      GFR: "60 이상",
      AST: "40 이하",
      ALT: "35 이하",
      yGPT: "남11-63 여8-35",
    },
    {
      refType: "질환의심",
      BMI: "25 이상",
      bloodPressure: "140/90 이상",
      fastingBloodGlucose: "126 이상",
      totalCholesterol: "240 이상",
      LDLCholesterol: "160 이상",
      triglyceride: "200 이상",
      AST: "51 이상",
      ALT: "51 이상",
    },
  ],
  resultList: [
    {
      caseType: "0",
      checkupType: "일반",
      checkupDate: "2025-04-18",
      organizationName: "서울건강검진센터",
      infantsCheckupList: [],
      infantsDentalList: [],
    },
    {
      caseType: "0",
      checkupType: "일반",
      checkupDate: "2023-05-02",
      organizationName: "한마음종합병원",
      infantsCheckupList: [],
      infantsDentalList: [],
    },
    {
      caseType: "0",
      checkupType: "일반",
      checkupDate: "2021-06-11",
      organizationName: "서울건강검진센터",
      infantsCheckupList: [],
      infantsDentalList: [],
    },
  ],
};
